### ISSUE TITLE
MultiScripts doesn't seems to load

### ISSUE THREAD

**Issue by michaelKurowski** [djxy/MultiScripts#9]
Multiscript fails on startup:
[16:56:42] [Server thread/ERROR] [Sponge]: Could not pass GameInitializationEvent$Impl to Plugin{id=multiscripts, name=MultiScripts, version=1.0, authors=[Djxy], source=mods\multiscripts-5.1.0.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/eventgencore/PropertySearchStrategy
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_131]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_131]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_131]
	at io.github.djxy.multiscripts.java.Converters.addConverters(Converters.java:43) ~[Converters.class:?]
	at io.github.djxy.multiscripts.sponge.Main.onGameInitializationEvent(Main.java:77) ~[Main.class:?]
	at org.spongepowered.common.event.listener.GameInitializationEventListener_Main_onGameInitializationEvent3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-6.1.0-BETA-5]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:349) [SpongeEventManager.class:1.11.2-6.1.0-BETA-5]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:366) [SpongeEventManager.class:1.11.2-6.1.0-BETA-5]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:370) [SpongeEventManager.class:1.11.2-6.1.0-BETA-5]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:198) [SpongeImpl.class:1.11.2-6.1.0-BETA-5]
	at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:145) [SpongeVanilla.class:1.11.2-6.1.0-BETA-5]
	at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$zob000(SourceFile:1234) [lh.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:186) [lh.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:436) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.eventgencore.PropertySearchStrategy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 17 more
Caused by: java.lang.NullPointerException
[16:56:42] [Server thread/INFO] [Sponge]: Successfully loaded and initialized plugins.

I use JDK to run the server.

**Comment by djxy** [comment]
MultiScripts is only working with API 5.0 and API 5.1.0. I didn't tested with the API 6.1.0.

**Comment by michaelKurowski** [comment]
_[17:12:41 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Loading Sponge plugins
        at org.spongepowered.server.plugin.PluginReporter.crash(PluginReporter.java:124) ~[PluginReporter.class:1.9.4-5.
0.0-BETA-82]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugins(VanillaPluginManager.java:72) ~[VanillaPlugi
nManager.class:1.9.4-5.0.0-BETA-82]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:172) ~[SpongeVanilla.class:1.9.4-5.0.
0-BETA-82]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$0(SourceFile:61) ~[lb.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:111) ~[lb.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:428) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: org.spongepowered.common.plugin.SpongeApiContainer cannot be cast to org.sponge
powered.api.plugin.PluginContainer
        at org.spongepowered.server.launch.plugin.PluginCandidate.collectDependencies(PluginCandidate.java:164) ~[sponge
vanilla-1.9.4-5.0.0-BETA-82.jar:1.9.4-5.0.0-BETA-82]
        at org.spongepowered.server.plugin.VanillaPluginManager.checkRequirements(VanillaPluginManager.java:81) ~[Vanill
aPluginManager.class:1.9.4-5.0.0-BETA-82]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugins(VanillaPluginManager.java:70) ~[VanillaPlugi
nManager.class:1.9.4-5.0.0-BETA-82]
        ... 5 more_


Looks like it doesn't works for 5 too.

**Comment by djxy** [comment]
It worked when I tested, but it is a while ago. I don't support this plugin anymore, so you will have to figure it out by yourself or find something else.

I'm sorry for the inconvenience.
